/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package phunk;

import javax.swing.JOptionPane;
import slittclient.Main;

/**
 *
 * @author Fredrik
 */
public class Tilbakemelding2 extends javax.swing.JFrame {

    /**
     * Creates new form Tilbakemelding2
     */
    public Tilbakemelding2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tilbakeside = new javax.swing.JLayeredPane();
        overskriftTilbakeM = new javax.swing.JLabel();
        åpne = new javax.swing.JButton();
        statusbilde = new javax.swing.JLabel();
        BackToTil = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1600, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
        );

        tilbakeside.setPreferredSize(new java.awt.Dimension(1600, 900));

        overskriftTilbakeM.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        overskriftTilbakeM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Tilbakemelding overskrift.png"))); // NOI18N

        åpne.setText("åpneTilbakemelding");
        åpne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                åpneActionPerformed(evt);
            }
        });

        statusbilde.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Tilbakemelding status.png"))); // NOI18N

        BackToTil.setText("jLabel3");
        BackToTil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackToTilMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout tilbakesideLayout = new javax.swing.GroupLayout(tilbakeside);
        tilbakeside.setLayout(tilbakesideLayout);
        tilbakesideLayout.setHorizontalGroup(
            tilbakesideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tilbakesideLayout.createSequentialGroup()
                .addGroup(tilbakesideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tilbakesideLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(BackToTil, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(373, 373, 373)
                        .addComponent(overskriftTilbakeM))
                    .addGroup(tilbakesideLayout.createSequentialGroup()
                        .addGap(534, 534, 534)
                        .addGroup(tilbakesideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(åpne, javax.swing.GroupLayout.PREFERRED_SIZE, 507, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(tilbakesideLayout.createSequentialGroup()
                                .addGap(63, 63, 63)
                                .addComponent(statusbilde)))))
                .addGap(0, 461, Short.MAX_VALUE))
        );
        tilbakesideLayout.setVerticalGroup(
            tilbakesideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tilbakesideLayout.createSequentialGroup()
                .addGroup(tilbakesideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(overskriftTilbakeM)
                    .addGroup(tilbakesideLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(BackToTil, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(79, 79, 79)
                .addComponent(åpne, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(117, 117, 117)
                .addComponent(statusbilde)
                .addGap(0, 294, Short.MAX_VALUE))
        );
        tilbakeside.setLayer(overskriftTilbakeM, javax.swing.JLayeredPane.DEFAULT_LAYER);
        tilbakeside.setLayer(åpne, javax.swing.JLayeredPane.DEFAULT_LAYER);
        tilbakeside.setLayer(statusbilde, javax.swing.JLayeredPane.DEFAULT_LAYER);
        tilbakeside.setLayer(BackToTil, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tilbakeside, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tilbakeside, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackToTilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackToTilMouseClicked
        Tilbakemelding tbm=new Tilbakemelding();
        Tilbakemelding2.this.setVisible(false);
         tbm.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_BackToTilMouseClicked

    private void åpneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_åpneActionPerformed
   
    if(Main.Godkjenning(åpne.getText())){
        JOptionPane.showMessageDialog(tilbakeside, "Modul er godkjent");
      
    }
    else{
         JOptionPane.showMessageDialog(tilbakeside, "Modul er ikke godkjent");
    }
    
    }//GEN-LAST:event_åpneActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tilbakemelding2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tilbakemelding2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tilbakemelding2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tilbakemelding2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tilbakemelding2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BackToTil;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel overskriftTilbakeM;
    private javax.swing.JLabel statusbilde;
    private javax.swing.JLayeredPane tilbakeside;
    private javax.swing.JButton åpne;
    // End of variables declaration//GEN-END:variables

    private void jTable(boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
